### PR TITLE
[SUBMISSION] December 2024 Completion of Module 1

### PR DESCRIPTION
**Pull request by Knight7561**
# December 2024 Student Submission

## Module Completed
- [x] Module 1: Instruction Tuning
- [ ] Module 2: Preference Alignment
- [ ] Module 3: Parameter-efficient Fine-tuning
- [ ] Module 4: Evaluation
- [ ] Module 5: Vision-language Models
- [ ] Module 6: Synthetic Datasets
- [ ] Module 7: Inference
- [ ] Module 8: Deployment

## Changes Made
Describe what you've done in this PR:
1. What concepts did you learn?
- Tokenisation, Reading datasets from HF, fine tuning smol models and how tokinzer module is contained
2. What changes or additions did you make?
- Added comments for better understanding, will add additional examples in the future work
3. Any challenges you faced?
- Nothing for this module

## Notebooks Added/Modified
List any notebooks you've added or modified:
- [x] Added new example in `module_name/student_examples/my_example.ipynb`
- [x] Modified existing notebook with additional examples
- [x] Added documentation or comments

## Checklist

- [x] I have read the module materials
- [x] My code runs without errors
- [x] I have pushed models and datasets to the huggingface hub
- [x] My PR is based on the `december_2024` branch

## Questions or Discussion Points
Add any questions you have or points you'd like to discuss:
1. 
2. 

## Additional Notes
Any other information that might be helpful for reviewers:

### CODE REVIEW

**Comment by Knight7561** [comment]
Please let me know any comments or if any changes needed

**Comment by burtenshaw** [comment]
Hey @Knight7561 

Thanks for the submission! Could you complete these steps to submit:
- merge latest changes from main
- ensure all work is only in `{module}/student_examples/{student}`
- review another student's PR and mention me!

🚀

**Comment by Knight7561** [comment]
So, @burtenshaw  you want me to:
1. merge latest code from `https://github.com/huggingface/smol-course/tree/main` to this learn branch and target the PR to December-2024 branch ?
2. all my code is under students example plus additional base code answering the questions.
3. Do you want me to pull from December-2024 branch also to this PR.

**Comment by Knight7561** [comment]
@burtenshaw  Created a better PR at #112 , if that seems right, I would go ahead and delete this PR after you confirm.

**Comment by burtenshaw** [comment]
@Knight7561 No worries. Nice work on improving. I'll close it.

**Pull request closed without merging**
