### PR TITLE
[SUBMISSION] Completion of Instruction Tuning on the-stack-smol

### PR DESCRIPTION
**Pull request by ash-01xor**
### Module completed 

 - [x] Module 1: Instruction Tuning

### Changes Made
- Got to understand the chat template structure and particular how to implement it for datasets that aren't formatted as question answer pairs directly.
- Had issues in converting the-stack-smol code dataset into chatml structure, however, reading guides about TRL helped a lot.
- Trained the Smol-instruct model on bigcode/the-stack-smol dataset, particularly on Python dataset
- Uploaded the model to my [hub](https://huggingface.co/collections/peaceAsh/smol-course-models-674fee07e838eaae748b6540) and created a collection to store the models trained for each upcoming chapter 
- Updated gitignore file to not include the files generated after the training process.

### Notebooks Added/Modified
-  [x] Modified existing notebook with additional examples

### Checklist

- [x]    I have read the module materials
- [x]     My code runs without errors
- [x]     I have pushed models and datasets to the huggingface hub
- [x]     My PR is based on the december_2024 branch

### Questions or Discussion Points
- Would be glad to understand how to debug when converting datasets not in chatml formats to one such .  Question such as what columns needs to be present , prompts that aid in better dataset creation etc. 
- A guide on such practice could be helpful as not all datasets are adjusted to that particular format. I'm open to the idea for  collaborating on it as well if possible

### CODE REVIEW

**Comment by ash-01xor** [comment]
Do let me know if there are any changes i have to make @burtenshaw

**Comment by burtenshaw** [comment]
Thanks for your submission @ash-01xor .

I've improved the chat templates page. 

I agree that the notebook could be improved to make clearer the expected results. Is this something you'd like to collaborate on?

**Comment by ash-01xor** [comment]
Can you elaborate on it @burtenshaw , i don't get you completely

**Comment by ash-01xor** [comment]
Yea sure done , probably we can discuss more about this in discord or as you prefer ?

**Comment by ash-01xor** [comment]
Well can you help me out in resolving the conflicts such that we can merge the PR. Since i finished doing the exercises before the other changes were made.

**Comment by burtenshaw** [comment]
This looks great. Could you move your notebook to a location other than the original notebook. For example, like this:

`{module}/notebooks/students/{student_name}/{notebook}`

**Comment by ash-01xor** [comment]
Do you mind explaining how to do it ? , do i have to download the notebooks from the existing branch , create another branch and then upload it in the link as you say

**Comment by burtenshaw** [comment]
No worries. I moved the work for you. You'll now see your work in december-2024 branch.

Join the discord to Discuss:

https://discord.com/channels/879548962464493619/1313889336907010110

**Pull request merged**
